vich_uploader:
    db_driver: orm

    mappings:
       galeria_image:
           uri_prefix: /img/galerias
           upload_destination: '%kernel.project_dir%/public/build/img/galerias'

       muestra_carrera:
           uri_prefix: /img/muestras_carrera
           upload_destination: '%kernel.project_dir%/public/build/img/muestras_carrera'

       producto_carrera:
           uri_prefix: /img/productos_carrera
           upload_destination: '%kernel.project_dir%/public/build/img/productos_carrera'
