# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    contratos_directory: '%kernel.project_dir%/public/contratos'

twig:

    globals:
        galerias: '@App\Services\Galerias'
        resegnias: '@App\Services\Resegnias'
        arguments: [ "@doctrine.orm.entity_manager" ]

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Sonata Admin Services

    admin.user_admin:
        class: App\Admin\UserAdmin
        arguments: [~, App\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Usuarios, label: Todos, 'icon': '<i class="fa fa-users"></i>'}
        public: true

    admin.user_administrador:
        class: App\Admin\AdministradorAdmin
        arguments: [~, App\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Usuarios, label: Administradores, 'icon': '<i class="fa fa-users"></i>'}
        public: true

    admin.user_carrera:
        class: App\Admin\UserCarreraAdmin
        arguments: [~, App\Entity\UserCarrera, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Usuarios, label: Usuarios Carrera, 'icon': '<i class="fa fa-users"></i>'}
        public: true

    admin.grupo_carrera:
        class: App\Admin\GrupoCarreraAdmin
        arguments: [~, App\Entity\GrupoCarrera, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Carreras, label: Grupos Carrera, 'icon': '<i class="fa fa-graduation-cap"></i>' }
        public: true

    admin.galeria:
        class: App\Admin\GaleriaAdmin
        arguments: [~, App\Entity\Galeria, App\Controller\GaleriaAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Galerías, label: Galerías , 'icon': '<i class="fa fa-image"></i>' }
        public: true

    admin.image_gallery_academica:
        class: App\Admin\ImageGalleryAcademicaAdmin
        arguments: [~, App\Entity\ImageGallery, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Galerías, label: Imágenes Académica, 'icon': '<i class="fa fa-image"></i>' }
        public: true

    admin.image_gallery_social:
        class: App\Admin\ImageGallerySocialAdmin
        arguments: [~, App\Entity\ImageGallery, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Galerías, label: Imágenes Social, 'icon': '<i class="fa fa-image"></i>' }
        public: true

    admin.resegnia:
        class: App\Admin\ResegniaAdmin
        arguments: [~, App\Entity\Resegnia, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Reseñas, label: Reseñas Usuarios, 'icon': '<i class="fa fa-comment"></i>'}
        public: true

    admin.universidad:
        class: App\Admin\UniversidadAdmin
        arguments: [~, App\Entity\Universidad, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin, label: Universidad, 'icon': '<i class="fa fa-database"></i>' }
        public: true

    admin.especialidad_carrera:
        class: App\Admin\EspecialidadCarreraAdmin
        arguments: [~, App\Entity\EspecialidadCarrera, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin, label: Especialidades Carreras, 'icon': '<i class="fa fa-database"></i>' }
        public: true

    admin.user_carrera_base:
        class: App\Admin\UserCarreraBaseAdmin
        arguments: [~, App\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin, label: Usuarios Carrera Base, 'icon': '<i class="fa fa-database"></i>'}
        public: true

    admin.muestras_carrera:
        class: App\Admin\MuestrasCarreraAdmin
        arguments: [~, App\Entity\MuestrasCarrera, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin, label: Muestras Carrera }
        public: true

    admin.productos_carrera:
        class: App\Admin\ProductosCarreraAdmin
        arguments: [~, App\Entity\ProductosCarrera, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin, label: Productos Carrera }
        public: true

    admin.muestras_carrera_grupo_carrera:
        class: App\Admin\MuestrasCarreraGrupoCarreraAdmin
        arguments: [~, App\Entity\MuestrasCarreraGrupoCarrera, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Carreras, label: Muestras Grupos Carrera}
        public: true

    admin.productos_carrera_grupo_carrera:
        class: App\Admin\ProductosCarreraGrupoCarreraAdmin
        arguments: [~, App\Entity\ProductosCarreraGrupoCarrera, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Carreras, label: Productos Grupos Carrera}
        public: true

    admin.profesor_carrera:
        class: App\Admin\ProfesorCarreraAdmin
        arguments: [~, App\Entity\ProfesorCarrera, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin, label: Profes Carrera }
        public: true

    admin.profesor_grupo_carrera:
        class: App\Admin\ProfesorGrupoCarreraAdmin
        arguments: [~, App\Entity\ProfesorGrupoCarrera, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Carreras, label: Profes Grupos Carrera }
        public: true

    admin.cuadrantes:
        class: App\Admin\CuadrantesAdmin
        arguments: [~, App\Entity\Cuadrantes, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin, label: Cuadrantes Carrera}
        public: true

    admin.cuadrantes_grupos_carrera:
        class: App\Admin\CuadrantesGruposCarreraAdmin
        arguments: [~, App\Entity\CuadrantesGruposCarrera, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Carreras, label: Cuadrantes Grupos Carrera }
        public: true

    admin.fecha_cuadrante_grupo_carrera:
        class: App\Admin\FechaCuadranteGrupoCarreraAdmin
        arguments: [~, App\Entity\FechaCuadranteGrupoCarrera, App\Controller\FechaCuadranteGrupoCarreraAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Carreras, label: Generar Citas }
        public: true

    admin.citas_fecha_cuadrante_grupo_carrera:
        class: App\Admin\CitasFechaCuadranteGrupoCarreraAdmin
        arguments: [~, App\Entity\CitasFechaCuadranteGrupoCarrera, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Carreras, label: Citas Carrera }
        public: true

    admin.color_becas_carrera:
        class: App\Admin\ColorBecasCarreraAdmin
        arguments: [~, App\Entity\ColorBecasCarrera, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin, label: Color Becas Carrera }
        public: true

    admin.color_becas_carrera_grupo_carrera:
        class: App\Admin\ColorBecasCarreraGrupoCarreraAdmin
        arguments: [~, App\Entity\ColorBecasCarreraGrupoCarrera, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Carreras, label: Color Becas Carreras}
        public: true

    admin.proceso_orla_grupo:
        class: App\Admin\ProcesoOrlaGrupoAdmin
        arguments: [~, App\Entity\ProcesoOrlaGrupo, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Carreras, label: Proceso Orlas }
        public: true

    admin.orla_provisional_grupos_carrera:
        class: App\Admin\OrlaProvisionalGruposCarreraAdmin
        arguments: [~, App\Entity\OrlaProvisionalGruposCarrera, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Carreras, label: Orla Provisional Carrera }
        public: true
